### ISSUE TITLE
Did not have user consent when expose web API in B2C tenant

### ISSUE THREAD

**Issue by swiftPeter** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#329]
I follow the document: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/4-WebApp-your-API/4-2-B2C/README-incremental-instructions.md#register-the-service-app-todolistservice-aspnetcore-webapi

In step 6, it mentions "user consent display name", but I did not see user consent in B2C tenant when exposing web API, this document seems like for B2B tenant rather than B2C, but it in B2C document path "active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-2-B2C/README-incremental-instructions.md" 

This really confused me, please let me know if there is the wrong document attached in B2C path

**Comment by TiagoBrenck** [comment]
The document is correct. Did you create your own applications and changed all the configs in the projects [Step 3](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/4-WebApp-your-API/4-2-B2C/README-incremental-instructions.md#step-3--configure-the-sample-to-use-your-azure-ad-tenant)?

**Comment by swiftPeter** [comment]
@TiagoBrenck Hi Tiago, this document is correct but this document is for Azure AD tenant, not for B2C tenant, did Azure AD tenant mentioned in this document refer to B2B tenant? If so, this document is a wrong path in B2C document, because I find this document path is for B2C but actually this article is for B2B rather than B2C

I think put this article to B2C document path active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-2-B2C/README-incremental-instructions.md" will confuse lots of people

**Comment by TiagoBrenck** [comment]
Sorry @swiftPeter I just checked the Azure Portal for B2C, and it seems that they change it. Indeed the field for user consent when creating a scope is not there. I will start an internal thread and I will let you know when we fix this.

Thanks for opening the issue.

**Comment by swiftPeter** [comment]
Hi @TiagoBrenck, I saw the document has been changed, I think you could close this issue, appreciate your help.

**Comment by TiagoBrenck** [comment]
Thanks.

**Comment by the-vampiire** [comment]
@TiagoBrenck can you confirm whether AD B2C allows for requesting **user consent**? i can not find an answer to this anywhere. it has been driving me insane and after another rabbit hole i end up on this issue.

all i have been able to do is grant tenant-wide permissions as an admin. but i would like a user to view a consent screen.

i do not follow how an *authorization* can be taken without the user consenting (authorizing) to the scopes. is this not the entire purpose of oauth?

use case:

- an API application exposes a `user_impersonation` scope
- a Client application requests an access token with this scope to make requests to the API on behalf of the authenticated user

> API

- under **Expose an API** settings
- exposes `user_impersonation` scope
  - **i do not see any option to designate the user consent of this scope** (it only shows admin consent)

> Client

- under **API Permissions** settings
- i must provide **tenant-wide admin consent** for the ``user_impersonation`` scope exposed by the API
- otherwise i receive the `AADB2C90205` ("application does not have sufficient permissions...") error

now when a user signs in they do not ever see a consent screen. this seems strange to me. shouldnt the user have to **consent** (authorize) the Client application to impersonate them in requests to the API application?

**Comment by the-vampiire** [comment]
> when exposing the scope for the API application

it implies that there should be a way to request **user consent**:

> ...request that a **user** or admin **consent**...

![image](https://user-images.githubusercontent.com/25523682/88493325-15612500-cf76-11ea-84ae-1f61f678f8c0.png)

but when adding a new scope the only option is admin consent required:

![image](https://user-images.githubusercontent.com/25523682/88493355-3f1a4c00-cf76-11ea-9357-d12b2a059996.png)

> when assigning the API permissions on the Client application 

the permission type is correctly classified as **delegated**. but then it states that admin consent is required:

![image](https://user-images.githubusercontent.com/25523682/88493394-75f06200-cf76-11ea-9988-0deae54a26a5.png)

unless i choose to grant **tenant-wide** permission as an admin it will not work

**Comment by the-vampiire** [comment]
is this because both the Client and API applications are registered in my tenant. so this not considered a **third-party delegation** as seen in traditional OAuth uses?

while i can rationalize the logic here i dont agree with it and think there should be some explanation around this behavior.

i believe (and according to the highlighted text when exposing a scope) that a user should be prompted for this consent **whether the applications are all organization owned or otherwise**. this is the purpose of OAuth. afaik the spec does not describe forked paths or designation between organization-owned or third-party.

this has been very frustrating. there is no documentation about this subject or how to configure user consent anywhere that i have seen.

**Comment by jmprieur** [comment]
@the-vampiire : no this is not because both apps are registered in your tenant (unless you have granted admin consent, in which case the users don't need to consent any longer)

@nickgmicrosoft can you please help?

**Comment by the-vampiire** [comment]
that is exactly what i did - grant tenant-wide admin consent. 

but i am confused why there appears to be no mechanism or documentation about setting other more granular consents (app, user). 

particularly user consent. it seems like a natural choice to me in the context of oauth with b2c.

**Comment by jmprieur** [comment]
I'll let @nickgmicrosoft elaborate. It might be that for the moment, this needs to be edited in the app manifest, but I'm not sure. @jennyf19 would you know?

**Comment by the-vampiire** [comment]
last i checked it wasnt available. but if you know there is support for this from the CLI or making raw requests to the azure REST API to configure this that is fine by me.

thank you again for tagging the experts. sorry if i came across as aggressive i am just really frustrated after scouring every resource i could find on the subject.

**Comment by nickgmicrosoft** [comment]
Hi @the-vampiire ,

Apologies for the confusion. To clarify, Azure AD B2C does not support user consent out of the box at this time. Thus, all scopes must be given admin consent as you found.

You can implement your own consent logic using custom policies as seen in [this](https://github.com/azure-ad-b2c/samples/tree/master/policies/service-consent) community sample.
