### ISSUE TITLE
"AccountController" with Area "AzureAd" and "SignOut" missing

### ISSUE THREAD

**Issue by twcarnahan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

two questions:
 Where is the "AccountController" with Area "AzureAd" and "SignOut"; how do we change the logout path?
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by twcarnahan** [comment]
Ultimately, we are trying to use post_logout_redirect_uri to point users back to home page after signout

**Comment by Tloch95** [comment]
It looks as if the AccountController was deleted in [commit 4bbfd9e3f720c2bc5a5958f373b8f3ced125af2f](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/4bbfd9e3f720c2bc5a5958f373b8f3ced125af2f).

**Comment by jmprieur** [comment]
@Tloch95 @twcarnahan : this is because the controller is now part of ASP.NET Core itself: see https://github.com/aspnet/AspNetCore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs

In order to change the logout path, you might want to subscribe to one of the OpenIDConnect events, for instance `OnRedirectToIdentityProviderForSignOut ` as described here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/ee3627031bad6027c69cc79a5ee43af8a9eb4802/Startup.cs#L84-L95

**Comment by twcarnahan** [comment]
services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.Authority = options.Authority + "/v2.0/";

    options.TokenValidationParameters.ValidateIssuer = false;

    options.Events.OnSignedOutCallbackRedirect = (context) =>
    {

        context.Response.Redirect("/Home/About");
        context.HandleResponse();

        return Task.CompletedTask;
    };
});
The above solved my problem but really appreciate the events path to understanding; looks like your going to answer other questions the we have coming out. Thank you.
