### ISSUE TITLE
How to react to "Revoke sessions" or "Sign out from everywhere" actions from Azure AD

### ISSUE THREAD

**Issue by mitirazvan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#433]
Hi, 

We have integrated the Azure AD login support in IdentityServer v4 to allow users to authenticate using their Microsoft accounts. Everything works fine, but I can't find a way to get notified when one of these actions are triggered:

![image](https://user-images.githubusercontent.com/18382083/98518380-fe6de680-2277-11eb-8feb-2d88ad77fd77.png)
I'm trying to implement the single sign out support in IdentityServer for the external idp AzureAD. The solution with the logout url is not a valid case since we want to trigger the sign out from Azure Portal or Azure My Account, and I don't think any of these actions call the end_session_endpoint.

1. What is happening when the "Revoke sessions" button is pressed? 
2. What is happening when the "Sign out everywhere" button is pressed? 

Is there any sample code that handles these actions?

The azure ad integration code:

           services.AddAuthentication()
                 .AddOpenIdConnect("azuread", "Azure AD", options => configuration.Bind("AzureAd", options));
            services.Configure<OpenIdConnectOptions>("azuread", options =>
            {
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Scope.Add("offline_access");
                options.TokenValidationParameters.ValidateIssuer = true;
                options.TokenValidationParameters.IssuerValidator = AadIssuerValidator.ValidateAadIssuer;
                options.GetClaimsFromUserInfoEndpoint = true;
                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                options.SaveTokens = true;                
                options.Events = new OpenIdConnectEvents()
                {

As for the events, we only handle the OnRemoteFailure. I thought that maybe If I can implement a mechanism that polls the access_token using the refresh_token might work, so if the refresh_token gets invalidated, then I can start the sign out for that user in IDS. But this will work only if the refresh_token is invalidated by the above actions. 

For our IdentityServer users when we want to force sign out someone, we have added in the id_token the security_stamp as a new claim and from the client application we check this claim to see if it was changed by calling the user info endpoint. This is somehow implemented as a polling mechanism triggered by the CookieAuthentication->OnValidateIdentity method.

**Comment by jmprieur** [comment]
@kalyankrishna1 @Shama-K : would you know?

**Comment by hpsin** [comment]
In both cases, these revoke all refresh tokens issued before the button was clicked. No signout message is sent to applications, so there is no signal to react to.  This is because Azure AD uses "front-channel signout" when the user clicks signout normally (e.g. from within an application).  The session cookie within the Azure AD login page contains a list of all the apps that the user has signed into during that session, and opens iframes to each of those sites at their logout URI.  The RPs then delete their cookies for that user, so the user is signed out of the app. 

In the situations described here, since it's for all sessions, not just the current one, this logout signal cannot be done.  Apps must be sure to gracefully handle refresh tokens no longer working - that's all that's expected here.

**Comment by jmprieur** [comment]
Proposing to close this issue as this was answered.
