### ISSUE TITLE
Bug in 5-2 GraphHelper.cs

### ISSUE THREAD

**Issue by davidopstack** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#455]
This function is wrong due to out of place brackets.  Unless you have an overage this will never return any groups the way its written.

Its currently this:
-=-=-=-=-=-=-=-

```CSharp
public static async Task<List<string>> GetSignedInUsersGroups(TokenValidatedContext context)
        {
            List<string> groupClaims = new List<string>();

            // Checks if the incoming token contained a 'Group Overage' claim.
            if (HasOverageOccurred(context.Principal))
            {
                // Gets group values from session variable if exists.
                groupClaims = GetUserGroupsFromSession(context.HttpContext.Session);
                if (groupClaims?.Count > 0)
                {
                    return groupClaims;
                }
                else
                {
                    groupClaims = await ProcessUserGroupsForOverage(context);
                }
            }
            return groupClaims;
        }

```

Should be this
=-=-=-=-=-=-
```CSharp
public static async Task<List<string>> GetSignedInUsersGroups(TokenValidatedContext context)
        {
            List<string> groupClaims = new List<string>();

            // Checks if the incoming token contained a 'Group Overage' claim.
            if (HasOverageOccurred(context.Principal))
            {
                // Gets group values from session variable if exists.
                groupClaims = GetUserGroupsFromSession(context.HttpContext.Session);
                if (groupClaims?.Count > 0)
                {
                    return groupClaims;
                }
          }
          else
          {
                groupClaims = await ProcessUserGroupsForOverage(context);
          }
          return groupClaims;
        }

```

**Comment by Shama-K** [comment]
@davidopstack, When there is no overage scenario then you will find the groups in claims collection. Processing is required for overage only.

GetUserGroupsFromSession method is called to get group values from session(**groupClaims**) if exists. If session does not contain groups claim then it will call ProcessUserGroupsForOverage method to retrieve groups. 
ProcessUserGroupsForOverage method makes calls Microsoft Graph to fetch the group membership of the authenticated user and adds the groups in a session(**groupClaims**).

Please let me know if it resolves the issue.

**Comment by davidopstack** [comment]
The way the function is written currently it returns a null value for group claims if there is no overage condition.

**Comment by davidopstack** [comment]
if (HasOverageOccurred(context.Principal))
        {
        <code>
        }
 return groupClaims;

thats what its doing.  NULL OBJECT

**Comment by jmprieur** [comment]
@Shama-K can you please look at this issue?
cc: @kalyankrishna1

**Comment by Shama-K** [comment]
@davidopstack, Could you please check if your Startup.cs has following code:

services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(1);
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });

**Comment by davidopstack** [comment]
Shama-K

These options ARE in my startup.cs

Look at the logic.  Its just a curly braces issue.  It never ever will see the overage condition to go to the Graph API because the if - else logic isn't structured correctly.

The else logic is in the wrong if statement because you have your curly braces in the wrong place

**Comment by Shama-K** [comment]
Can you connect with me at this email address: v-lnushama At microsoft.com?

**Comment by jmprieur** [comment]
@Shama-K : where are we with this issue?

**Comment by jmprieur** [comment]
@davidopstack
The code in GraphHelper.cs is right. As @Shama-K explained:
- when a user is part of a group, and there is not [Group overage](https://docs.microsoft.com/azure/active-directory/develop/id-tokens#groups-overage-claim), you'll already find claims in the token named "group", which contain the name or id or ... what you have decided for the groups the user belongs to
- when the user belongs to too many groups, there is group overage. In that case:
  - the first time the [ProcessUserGroupsForOverage](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/8294c9d4504ec115b68552acc9e63c8d49c5d892/5-WebApp-AuthZ/5-2-Groups/Services/MicrosoftGraph-Rest/GraphHelper.cs#L88) method will extract the groups and put them in the session
  - the next times, the groups will be retrieved from the session by calling [GetUserGroupsFromSession](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/8294c9d4504ec115b68552acc9e63c8d49c5d892/5-WebApp-AuthZ/5-2-Groups/Services/MicrosoftGraph-Rest/GraphHelper.cs#L50)

In any case these 2 methods should only be called in the case there are group overages, as otherwise the groups will just be there.

If you are not seeing this:
- are you in a web app (the ID token would get the group), or in a web API (the access token would)
- What are you observing?
- What is the problem and what are the repro steps?

You might also want to have a look at [Configuring groups optional claims](https://docs.microsoft.com/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims) to be sure you are doing the right thing
