### ISSUE TITLE
Where is the .NET 5 sample code?

### ISSUE THREAD

**Issue by kwaazaar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#462]
Documentation and samples on Azure AD integration is a mess. I find samples for 2.2 or 3, but no samples for 5. It's also not clearly mentioned for what version the samples are.

**Comment by jmprieur** [comment]
@kwaazaar : we're sorry that you find that the documentation and samples are a mess.

For the 5.0 samples, just know that apps written for net core 3.1 code run seamlessly with ASP.NET for net 5.0. Microsoft.Identity.Web builds for both and the CI/CD tests both. See for instance https://github.com/AzureAD/microsoft-identity-web/blob/bf8b06fa812521e99cd006edee8b50f100f0670c/tests/WebAppCallsMicrosoftGraph/WebAppCallsMicrosoftGraph.csproj#L3
So our recommendation is you take on the the sample and change the target framework to net5.0 and it will just work.

Could you please share other specifics about what is a mess? We spend a lot of time updating our samples, and appreciate your feedback, and are committed to doing better.
As far as the documentation, it's available from https://aka.ms/aaddevsamplesv2 with a list of all the samples

**Comment by zhadjah9559** [comment]
I'm glad im not the only one who had trouble with this. I did a tech interview with a company and had to struggle with some of those docs unforunately. I hope they get reconfigured to be more understandable soon.

**Comment by jmprieur** [comment]
@zhadjah9559 thanks for the feedback. Can you please be specific? What, from your perspective would be better docs? if you had a magic wand, what would you do?

**Comment by aremo-ms** [comment]
@zhadjah9559 @kwaazaar 
I'm currently working on improving documentation for the samples. Will update soon.

**Comment by ataraxia89** [comment]
I've also had so many problems trying to follow how to integrate Azure B2C auth into a web app. My API is done, my web app is mostly done, I am redirected to the user login flow and get returned to my web app but the first time I try to get an access token it all falls over.

It started with a `MsalUIRequiredException: No Account or login hint was passed to the AcquireTokenSilent`, but then I found [this guide](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server) which captures the exception but then redirects me to /MicrosoftIdentity/Account/Challenge which throws a 404.

Like 98% of my app is ready but it's all stuck because I can't get a damn access token.

**Comment by jmprieur** [comment]
@ataraxia89 : 404 that is app crash. can you please log the exception?

**Comment by ataraxia89** [comment]
@jmprieur in the browser developer tools I see:

`Uncaught (in promise) WebSocket is not in the OPEN state` - in blazor.server.js
`Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.` - in blazor.server.js

**Comment by aremo-ms** [comment]
@ataraxia89 
Can you please update on this issue? Did you manage to overcome all failures? If not I'd like to address your concerns

**Comment by ataraxia89** [comment]
> @ataraxia89 Can you please update on this issue? Did you manage to overcome all failures? If not I'd like to address your concerns

For the [initial exception](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/462#issuecomment-934906818) I believe the issue was that either the user wasn't authenticated or the auth needed to be refreshed, not sure but in any case it needed to be caught as per the guide I posted.

The reason I was getting a 404 was because I needed to add the line below to the `Configure` method in `Startup.cs`:

```
app.UseEndpoints(
    endpoints =>
        {
            endpoints.MapControllers(); // << This line here
            endpoints.MapBlazorHub();
            endpoints.MapFallbackToPage("/_Host");
        });
```

My web app and API are both working properly now and are live.

**Comment by aremo-ms** [comment]
> > @ataraxia89 Can you please update on this issue? Did you manage to overcome all failures? If not I'd like to address your concerns
> 
> For the [initial exception](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/462#issuecomment-934906818) I believe the issue was that either the user wasn't authenticated or the auth needed to be refreshed, not sure but in any case it needed to be caught as per the guide I posted.
> 
> The reason I was getting a 404 was because I needed to add the line below to the `Configure` method in `Startup.cs`:
> 
> ```
> app.UseEndpoints(
>     endpoints =>
>         {
>             endpoints.MapControllers(); // << This line here
>             endpoints.MapBlazorHub();
>             endpoints.MapFallbackToPage("/_Host");
>         });
> ```
> 
> My web app and API are both working properly now and are live.

@ataraxia89  That's great to hear. Can you please advise what sample you've experienced issues with? I will need to check instruction per your feedback. Thanks in advance

**Comment by ataraxia89** [comment]
> @ataraxia89 That's great to hear. Can you please advise what sample you've experienced issues with? I will need to check instruction per your feedback. Thanks in advance

Well I can see that the code I was missing is in the example so I don't know if I missed this or what happened, a lot has been going on with this project since I originally commented above so I can't remember exactly.

**Comment by aremo-ms** [comment]
> > @ataraxia89 That's great to hear. Can you please advise what sample you've experienced issues with? I will need to check instruction per your feedback. Thanks in advance
> 
> Well I can see that the code I was missing is in the example so I don't know if I missed this or what happened, a lot has been going on with this project since I originally commented above so I can't remember exactly.

Ok, then. I'm closing the issue for now. Let us know for any other questions in a separate issue.
Thanks for your help
