### ISSUE TITLE
Teach a man to fish

### ISSUE THREAD

**Issue by GriffinGSA** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#99]
How about showing us how you created the Visual Studio Solution itself or am I missing something? What the community really needs is an example that demonstrates how to create an Web Application in Visual studio and get it to authenticate with oAuth, then finally adding RBAC to that sample application as well. Downloading an already created Web Application = "magic " in order to make this stuff work

**Comment by kalyankrishna1** [comment]
The various readme have a "Create the sample from the command line" section that shows how to build the sample from command line.
Note that, some of the samples , build on a previous one and would not have this step.

**Comment by TiagoBrenck** [comment]
@GriffinGSA, we try to document the code as much as possible and add the section "About the Code" on the readme to explain more about some key points in the sample. If you are missing a comment on an specific method, let us know which one so we can add it.

About the Visual Studio solution part, we usually start our samples using the templates provided by VS already. The templates provide us some simple Controllers, Views and some basic configurations (like the routes) that have nothing to deal with OAuth, so we don't mention them on the documentation because our focus in these samples is Azure Active Directory.

Thanks

**Comment by jmprieur** [comment]
Thanks for the feedback @GriffinGSA 
We'll add sections about creating the ASP.NET Core Web app project with Visual Studio in addition to with the command line (this produces the same result, but you are right that this might be easier to some users)

I'm a bit confused, though, by some of your comments. Could you please clarify, so that we are sure we don't miss something:

- Which README.md do you refer to?
Is it https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg#option-2-create-the-sample-from-the-command-line ?
- Did you notice that this sample is an incremental tutorial, and explains how to build the application (See [Scope of this tutorial](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#scope-of-this-tutorial)). If you did not, what would you advise us to do to make it more visible?

- What do you mean exactly about adding RBAC? can you please be more specific? Is it more than protecting the Web App by [roles](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles) and [groups](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups)
